# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_date', models.DateField(primary_key=True, serialize=False)),
                ('expense_detail', models.CharField(help_text="Enter the expense detail in form 'expense detail : expense ammount'", max_length=200)),
            ],
        ),
    ]
