# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyExpenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(),
        ),
    ]
