# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyExpenses', '0003_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_amount',
            field=models.FloatField(help_text='Enter expense amount', null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_detail',
            field=models.CharField(help_text='Enter expense details', max_length=200, null=True),
        ),
    ]
