# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyExpenses', '0004_auto_20170518_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_amount',
            field=models.DecimalField(decimal_places=10, help_text='Enter expense amount', max_digits=19, null=True),
        ),
    ]
