# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyExpenses', '0005_auto_20170518_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_amount',
            field=models.FloatField(help_text='Enter expense amount', null=True),
        ),
    ]
