# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyExpenses', '0006_auto_20170518_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
